# Generated by Django 5.2.5 on 2025-08-28 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('url', models.URLField(verbose_name='URL de Scraping')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='País')),
                ('lodgify_property_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lodgify Property ID')),
                ('lodgify_room_type_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lodgify Room Type ID')),
                ('lodgify_enabled', models.BooleanField(default=False, verbose_name='Sincronización Lodgify Habilitada')),
                ('price_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Ajuste de Precio (%)')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('pending', 'Pendiente')], default='active', max_length=20, verbose_name='Estado')),
                ('enabled', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hoteles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('manager', 'Manager'), ('viewer', 'Visualizador')], default='viewer', max_length=20, verbose_name='Rol')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('dark_mode', models.BooleanField(default=True, verbose_name='Modo Oscuro')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notificaciones por Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
        migrations.CreateModel(
            name='ScrapingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='Fecha de Entrada')),
                ('check_out', models.DateField(verbose_name='Fecha de Salida')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio')),
                ('currency', models.CharField(default='MXN', max_length=10, verbose_name='Moneda')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('success', 'Exitoso'), ('error', 'Error'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('scraped_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Scraping')),
                ('method', models.CharField(default='intelligent', max_length=50, verbose_name='Método de Scraping')),
                ('success', models.BooleanField(default=True, verbose_name='Éxito')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('lodgify_synced', models.BooleanField(default=False, verbose_name='Sincronizado con Lodgify')),
                ('lodgify_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Sincronización Lodgify')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraping_results', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'Resultado de Scraping',
                'verbose_name_plural': 'Resultados de Scraping',
                'ordering': ['-scraped_at'],
                'unique_together': {('hotel', 'check_in', 'check_out')},
            },
        ),
    ]
