# Generated by Django 5.2.5 on 2025-08-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='source',
            field=models.CharField(blank=True, max_length=50, verbose_name='Fuente'),
        ),
    ]
