# Generated by Django 5.2.5 on 2025-09-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel_description_hotel_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='lodgify_enabled',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='lodgify_property_id',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='lodgify_room_type_id',
        ),
        migrations.RemoveField(
            model_name='scrapingresult',
            name='lodgify_sync_at',
        ),
        migrations.RemoveField(
            model_name='scrapingresult',
            name='lodgify_synced',
        ),
        migrations.AddField(
            model_name='hotel',
            name='otasync_enabled',
            field=models.BooleanField(default=False, verbose_name='Sincronización OTASync Habilitada'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='otasync_pricing_plan_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='OTASync Pricing Plan ID'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='otasync_property_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='OTASync Property ID'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='otasync_room_type_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='OTASync Room Type ID'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='otasync_sync_days',
            field=models.IntegerField(default=20, verbose_name='Días de Sincronización'),
        ),
        migrations.AddField(
            model_name='scrapingresult',
            name='otasync_sync_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Sincronización OTASync'),
        ),
        migrations.AddField(
            model_name='scrapingresult',
            name='otasync_synced',
            field=models.BooleanField(default=False, verbose_name='Sincronizado con OTASync'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='url',
            field=models.URLField(max_length=1000, verbose_name='URL de Scraping'),
        ),
    ]
